# Generated by Django 3.1.5 on 2021-02-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_booking_ref',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
