# Generated by Django 3.1.5 on 2021-02-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210131_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
