# Generated by Django 3.1.5 on 2021-02-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20210204_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsummary',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
