# Generated by Django 3.1.5 on 2021-01-31 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactUsMessage',
        ),
    ]
