# Generated by Django 3.1.5 on 2021-01-31 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Paid but not confirmed', 'Paidbutnotconfirmed'), ('Confirmed but not paid', 'Confirmedbutnotpaid'), ('Paid and Confirmed', 'Paidandconfirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Booked', max_length=50),
        ),
    ]
