# Generated by Django 3.1.5 on 2021-01-31 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['booked_by', 'booked_on']},
        ),
    ]
