# Generated by Django 3.1.5 on 2021-01-30 10:13

from django.db import migrations, models
import django.db.models.deletion
import motorhomes.models


class Migration(migrations.Migration):

    dependencies = [
        ('motorhomes', '0002_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorhome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255, unique=True)),
                ('seats', models.IntegerField(default=2)),
                ('persons_to_sleep', models.IntegerField(default=2)),
                ('number_of_double_beds', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('Basic', 'Basic'), ('Comfort', 'Comfort'), ('Premium', 'Premium')], default='Comfort', max_length=50)),
                ('good_for_groups', models.CharField(choices=[('Single', 'Single'), ('Couple', 'Couple'), ('Family', 'Family')], default='Couple', max_length=50)),
                ('picture1', models.ImageField(upload_to=motorhomes.models.user_directory_path)),
                ('picture2', models.ImageField(upload_to=motorhomes.models.user_directory_path)),
                ('picture3', models.ImageField(upload_to=motorhomes.models.user_directory_path)),
                ('picture4', models.ImageField(upload_to=motorhomes.models.user_directory_path)),
                ('picture5', models.ImageField(upload_to=motorhomes.models.user_directory_path)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorhomes.vehicle')),
            ],
        ),
    ]
