# Generated by Django 3.1.5 on 2021-02-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorhomes', '0003_motorhome'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorhome',
            name='artricle1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motorhome',
            name='artricle2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motorhome',
            name='artricle3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motorhome',
            name='artricle4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
