# Generated by Django 3.1.5 on 2021-02-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorhomes', '0004_auto_20210201_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motorhome',
            old_name='artricle1',
            new_name='article1',
        ),
        migrations.RenameField(
            model_name='motorhome',
            old_name='artricle2',
            new_name='article2',
        ),
        migrations.RenameField(
            model_name='motorhome',
            old_name='artricle3',
            new_name='article3',
        ),
        migrations.RenameField(
            model_name='motorhome',
            old_name='artricle4',
            new_name='article4',
        ),
    ]
